import type { Metadata } from "next";
import Link from "next/link";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-50 text-gray-900">
        <nav className="flex gap-6 border-b bg-white px-6 py-4">
          <Link href="/" className="font-semibold">Home</Link>
          <Link href="/tasks" className="text-gray-600 hover:text-gray-900">Tasks</Link>
        </nav>
        <main className="mx-auto max-w-2xl p-6">{children}</main>
      </body>
    </html>
  );
}
